name: NodeJS with Webpack

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm init vite@latest
          npm install
          npm run build
      # 部署到 GitHub pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3 # 使用部署到 GitHub pages 的 action
        with:
          publish_dir: ./docs # 部署打包后的 dist 目录
          github_token: ${{ secrets.DEPLOY_SECRET }} # secret 名
          # user_name: 'skyfish-1024'
          # user_email: '1982452293@qq.com'
          commit_message: 自动部署 # 部署时的 git 提交信息，自由填写

